### ISSUE TITLE
Getting error while running docker

### ISSUE THREAD

**Issue by parameshnalla** [tugrulcan/docker-elk-filebeat#1]
While running the docker-compose getting this error. 

➜  docker-elk-filebeat git:(master) docker-compose build
ERROR: Named volume "f:\logs:/logs" is used in service "logstash" but no declaration was found in the volumes section.

Can you please have a look.

**Comment by atahanceylan** [comment]
@parameshnalla  You should change this one where your logs stored.For example I changed to - ./logs:/logs. It worked well.

**Comment by parameshnalla** [comment]
Thank you @atahanceylan
